/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppDebugIconsRouteImport } from './routes/app.debug-icons'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAddRouteImport } from './routes/app.add'
import { Route as AppEditIdRouteImport } from './routes/app.edit.$id'
import { Route as ApiPublicHooksSendRenewalRemindersRouteImport } from './routes/api/public/hooks/send-renewal-reminders'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugIconsRoute = AppDebugIconsRouteImport.update({
  id: '/debug-icons',
  path: '/debug-icons',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppEditIdRoute = AppEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksSendRenewalRemindersRoute =
  ApiPublicHooksSendRenewalRemindersRouteImport.update({
    id: '/api/public/hooks/send-renewal-reminders',
    path: '/api/public/hooks/send-renewal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/add': typeof AppAddRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/debug-icons': typeof AppDebugIconsRoute
  '/app/scan': typeof AppScanRoute
  '/app/': typeof AppIndexRoute
  '/app/edit/$id': typeof AppEditIdRoute
  '/api/public/hooks/send-renewal-reminders': typeof ApiPublicHooksSendRenewalRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/add': typeof AppAddRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/debug-icons': typeof AppDebugIconsRoute
  '/app/scan': typeof AppScanRoute
  '/app': typeof AppIndexRoute
  '/app/edit/$id': typeof AppEditIdRoute
  '/api/public/hooks/send-renewal-reminders': typeof ApiPublicHooksSendRenewalRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/add': typeof AppAddRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/debug-icons': typeof AppDebugIconsRoute
  '/app/scan': typeof AppScanRoute
  '/app/': typeof AppIndexRoute
  '/app/edit/$id': typeof AppEditIdRoute
  '/api/public/hooks/send-renewal-reminders': typeof ApiPublicHooksSendRenewalRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/scan'
    | '/signup'
    | '/terms'
    | '/app/add'
    | '/app/alerts'
    | '/app/billing'
    | '/app/debug-icons'
    | '/app/scan'
    | '/app/'
    | '/app/edit/$id'
    | '/api/public/hooks/send-renewal-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/scan'
    | '/signup'
    | '/terms'
    | '/app/add'
    | '/app/alerts'
    | '/app/billing'
    | '/app/debug-icons'
    | '/app/scan'
    | '/app'
    | '/app/edit/$id'
    | '/api/public/hooks/send-renewal-reminders'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/scan'
    | '/signup'
    | '/terms'
    | '/app/add'
    | '/app/alerts'
    | '/app/billing'
    | '/app/debug-icons'
    | '/app/scan'
    | '/app/'
    | '/app/edit/$id'
    | '/api/public/hooks/send-renewal-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksSendRenewalRemindersRoute: typeof ApiPublicHooksSendRenewalRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debug-icons': {
      id: '/app/debug-icons'
      path: '/debug-icons'
      fullPath: '/app/debug-icons'
      preLoaderRoute: typeof AppDebugIconsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add': {
      id: '/app/add'
      path: '/add'
      fullPath: '/app/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/edit/$id': {
      id: '/app/edit/$id'
      path: '/edit/$id'
      fullPath: '/app/edit/$id'
      preLoaderRoute: typeof AppEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/send-renewal-reminders': {
      id: '/api/public/hooks/send-renewal-reminders'
      path: '/api/public/hooks/send-renewal-reminders'
      fullPath: '/api/public/hooks/send-renewal-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRenewalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDebugIconsRoute: typeof AppDebugIconsRoute
  AppScanRoute: typeof AppScanRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditIdRoute: typeof AppEditIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDebugIconsRoute: AppDebugIconsRoute,
  AppScanRoute: AppScanRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditIdRoute: AppEditIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksSendRenewalRemindersRoute:
    ApiPublicHooksSendRenewalRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
